import java.util.*;
// You are given two strings, str1 and str2, of lengths n and m, respectively.

// A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

// If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
// If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
// Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

// Example 1:

// Input: str1 = "TFTF", str2 = "ab"

// Output: "ababa"

// Explanation:

// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.

// Return "ababa" since it is the lexicographically smaller string.

// Example 2:

// Input: str1 = "TFTF", str2 = "abc"

// Output: ""

// Explanation:

// No string that satisfies the conditions can be generated.

// Example 3:

// Input: str1 = "F", str2 = "d"

// Output: "a"

 

public class lexographicallySMallest {
     public static String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        char[] arr = new char[n+m-1];

        // filled string full with a so empty spaces filled with a so we get lexo graphically smallest string
        for (int i = 0; i < arr.length; i++) {
            arr[i] = 'a';
        }

        // where we got string[i]==T there we filled substing upto i to n-1 with str2   
        for (int i = 0; i < n; i++) {
            if(str1.charAt(i)=='T'){

             for(int j=0;j<m;j++){
                 arr[j+i]=str2.charAt(j);
                 }
            }
            else continue;
        }

        // again cheaking any sting accidently equals to that substing if yes we return empty string
        for (int i = 0; i < n; i++) {
            if(str1.charAt(i)=='F'){
               int flag=0;
                for(int j=0;j<m;j++){
                    char ch = str2.charAt(j);
                    if(arr[i+j]!=ch){
                        flag = 1;
                    }
                    if(flag==1) return "";
                }
             }
        }

        // verifiying true  constraint 
        for (int i = 0; i < n; i++) {
            if(str1.charAt(i)=='T'){

             for(int j=0;j<m;j++){
                 if(arr[i+j]==str2.charAt(j)) continue;
                 else return "";        
                 }
            }
            else continue;
        }

        return new String(arr);
    }

    public static void main(String args[]){
      System.out.println(generateString("F", "acfcfc"));
    }
}